# Generated by Django 4.0.1 on 2022-01-17 08:37

from django.db import migrations, models
import django.db.models.deletion
import leavestracker.apps.leaves.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employees_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(validators=[leavestracker.apps.leaves.validators.validate_date])),
                ('ended_at', models.DateField(validators=[leavestracker.apps.leaves.validators.validate_date, leavestracker.apps.leaves.validators.validate_end_date])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
    ]
