# Generated by Django 4.0.1 on 2022-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
