# Generated by Django 4.0.1 on 2022-01-17 11:19

from django.db import migrations, models
import leavestracker.apps.leaves.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='ended_at',
            field=models.DateField(validators=[leavestracker.apps.leaves.models.Leaves.validate_date, leavestracker.apps.leaves.models.Leaves.validate_end_date]),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='started_at',
            field=models.DateTimeField(validators=[leavestracker.apps.leaves.models.Leaves.validate_date]),
        ),
    ]
