END_DATE_BEFORE_START_DATE = "End date of a leave can't be before the start date."
LEAVE_EXISTS = "A leave already exists in this interval. You may delete the previous entry or change your new dates"
PAST_DATE = "You can't create a leave on this date or update this date as this date has passed."
LEAVE_DOES_NOT_EXIST = "Leave hasn't been applied for the selected dates or user."
SLACK_TITLE = "Folks that are AFK today"
