# Generated by Django 4.0.1 on 2022-01-14 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesmodel',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=b'I01\n', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
