# Generated by Django 4.0.1 on 2022-01-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_user'),
        ('employees', '0002_customuser'),
    ]

    operations = [
    ]
